FROM node:18-alpine AS builder
WORKDIR /app
COPY client/package.json ./client/
RUN cd client && npm install
COPY client ./client
RUN cd client && npm run build

FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
